name: Mirror to Organization

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.MIRROR_TOKEN }}

    - name: Mirror to organization repository
      env:
        MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add the organization repository as a remote
        git remote add org https://$MIRROR_TOKEN@github.com/ThePossibleZone/navigator-advisor.git
        
        # Push all branches and tags to the organization repository
        git push org --all --force
        git push org --tags --force
